shirts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^shirts/', views.listing, name='listing'),
    url(r'^shirt/(?P<pk>\d+)/', views.detail, name='detail'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^$', views.home, name='home'),
]

shirts4mikedjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('shirts.urls', namespace='shirts')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shirts/models.py
from django.db import models

# Create your models here.
class Size(models.Model):
    name = models.CharField(max_length=255)
    symbol = models.CharField(max_length=10)

    def __str__(self):
        return self.name


class Shirt(models.Model):
    name = models.CharField(max_length=255)
    img = models.ImageField()
    price = models.FloatField()
    paypal = models.CharField(max_length=13)
    sizes = models.ManyToManyField(Size)

    def __str__(self):
        return self.name

shirts/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=255, label='Name',)
    email = forms.EmailField(label='Email')
    message = forms.CharField(widget=forms.Textarea, label='Message')

shirts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse

import sendgrid

from .models import Shirt
from .forms import ContactForm


def listing(request):
    shirts = Shirt.objects.all()
    return render(request, 'shirts/listing.html', {'shirts': shirts})


def home(request):
    shirts = Shirt.objects.all().order_by('-id')[:4]
    return render(request, 'shirts/home.html', {'shirts': shirts})


def detail(request, pk):
    shirt = get_object_or_404(Shirt, pk=pk)
    return render(request, 'shirts/detail.html', {'shirt': shirt})


def contact(request):
    if request.POST:
        sg = sendgrid.SendGridClient("", "", raise_errors=True)

        subject = request.POST['name']
        text = request.POST['message']
        email = request.POST['email']

        message = sendgrid.Mail()
        message.add_to('charlie.thomas@attwoodthomas.net')
        message.set_subject(subject)
        message.set_text(text)
        message.set_from(email)

        try:
            sg.send(message)
            print("SENT")
        except sendgrid.SendGridClientError:
            None
        except sendgrid.SendGridServerError:
            None
        return redirect(reverse("shirts:home"))
    form = ContactForm(auto_id='%s')
    return render(request, 'shirts/contact.html', {'form': form})

shirts/templates/shirts/contact.html
{%  extends "layout.html" %}
{% block body %}
        <div class="section page">

        <div class="wrapper">

            <h1>Contact</h1>


            <p>I&rsquo;d love to hear from you! Complete the form to send me an email.</p>

            <form method="post" action="{% url 'shirts:contact' %}">
                {% csrf_token %}
                <table>
                    {{ form.as_table }}
                </table>
                <input type="submit" value="Send">

            </form>

        </div>

    </div>
{% endblock %}

shirts/templates/shirts/detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% block body %}
    <div class="section page">

        <div class="wrapper">

            <div class="breadcrumb"><a href="{% url 'shirts:listing' %}">Shirts</a> &gt; {{ shirt.name }} ></div>

            <div class="shirt-picture">
                <span>
                    <img src="{{ shirt.img.url }}" alt="{{ shirt.name }} ?>">
                </span>
            </div>

            <div class="shirt-details">

                <h1><span class="price">${{ shirt.price }}</span> {{ shirt.name }}</h1>

                <form target="paypal" action="https://www.paypal.com/cgi-bin/webscr" method="post">
                    <input type="hidden" name="cmd" value="_s-xclick">
                    <input type="hidden" name="hosted_button_id" value="{{ shirt.paypal }}">
                    <input type="hidden" name="item_name" value="{{ shirt.name }}">
                    <table>
                    <tr>
                        <th>
                            <input type="hidden" name="on0" value="Size">
                            <label for="os0">Size</label>
                        </th>
                        <td>
                            <select name="os0" id="os0">
                                {%  for size in shirt.sizes.all %}
                                    <option value="{{ size.name }}">{{ size.name }} </option>
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    </table>
                    <input type="submit" value="Add to Cart" name="submit">
                </form>

                <p class="note-designer">* All shirts are designed by Mike the Frog.</p>

            </div>

        </div>

    </div>
{% endblock %}

shirts/templates/shirts/home.html
 {% extends "layout.html" %}
{% load static from staticfiles %}
{% block body %}
    <div class="section banner">

			<div class="wrapper">

				<img class="hero" src="{% static "img/mike-the-frog.png" %}" alt="Mike the Frog says:">
				<div class="button">
					<a href="{% url 'shirts:listing' %}">
						<h2>Hey, I&rsquo;m Mike!</h2>
						<p>Check Out My Shirts</p>
					</a>
				</div>
			</div>

		</div>

		<div class="section shirts latest">

			<div class="wrapper">

				<h2>Mike&rsquo;s Latest Shirts</h2>

				<ul class="products">
                    {% for shirt in shirts %}<li><a href="{% url 'shirts:detail' pk=shirt.pk %}"><img src="{{ shirt.img.url }}" alt="{{ shirt.name }}"><p>View Details</p></a></li>{% endfor %}
				</ul>

			</div>

		</div>
{% endblock %}

shirts/templates/shirts/listing.html
{% extends "layout.html" %}
{% block body %}
    <div class="section shirts page">
        <div class="wrapper">
            <h1>Mike&rsquo;s Full Catalog of Shirts</h1>

            <ul class="products">
                {% for shirt in shirts %}<li><a href="{% url 'shirts:detail' pk=shirt.pk %}"><img src="{{ shirt.img.url }}"><p>View Details</p></a></li>{% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:400,700" type="text/css">
</head>
<body>

	<div class="header">
		<div class="wrapper">
			<h1 class="branding-title"><a href="{% url 'shirts:home' %}">Shirts 4 Mike</a></h1>
			<ul class="nav">
				<li class="shirts"><a href="{% url 'shirts:listing' %}">Shirts</a></li>
				<li class="contact"><a href="{% url 'shirts:contact' %}">Contact</a></li>
				<li class="cart"><a target="paypal" href="https://www.paypal.com/cgi-bin/webscr?cmd=_cart&amp;business=Q6NFNPFRBWR8S&amp;display=1">Shopping Cart</a></li>
			</ul>
		</div>
	</div>

	<div id="content">
	    {% block body %}{% endblock %}
	</div>

	<div class="footer">
		<div class="wrapper">
			<ul>
				<li><a href="http://twitter.com/treehouse">Twitter</a></li>
				<li><a href="https://www.facebook.com/TeamTreehouse">Facebook</a></li>
			</ul>
			<p>&copy;2015 Shirts 4 Mike</p>
		</div>
	</div>
</body>
</html>